services:
  server:
    build:
      context: .
      args:
        PUBLIC_URL: http://localhost:3000/
    ports:
      - 5000:80
    volumes:
      - data:/app/storage
    environment:
      - API_SECRET_KEY=${API_SECRET_KEY}
      - ADMINPWD=${ADMINPWD}
      - DBPATH=root:${DBPWD}@db:3306/default
      - DBDASHBOARDPATH=mysql+pymysql://root:${DBPWD}@db:3306/dashboard
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4
    # command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS dashboard;' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
      # - MYSQL_ROOT_PASSWORD=strong_password
    expose:
      - 3306
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 45s

volumes:
  db-data:
  data:

secrets:
  db-password:
    # file: db/password.txt
    environment: DBPWD
