"""v3

Revision ID: 5cec80e585d4
Revises: b87b040d03a8
Create Date: 2024-08-15 21:32:43.493366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cec80e585d4'
down_revision: Union[str, None] = 'b87b040d03a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('gameOpened', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'gameOpened')
    # ### end Alembic commands ###
