"""v2

Revision ID: 03058aaa8dbd
Revises: 1d7df12c47a2
Create Date: 2024-02-18 02:39:29.589759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy import orm
from data.race import Race
from data.role import Role

# revision identifiers, used by Alembic.
revision: str = '03058aaa8dbd'
down_revision: Union[str, None] = '1d7df12c47a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Race',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('winner', sa.String(length=8), nullable=True),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('startStr', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Race')),
    sa.UniqueConstraint('id', name=op.f('uq_Race_id'))
    )
    op.create_table('UserRace',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('fk_UserRace_userId_User')),
    sa.PrimaryKeyConstraint('userId', name=op.f('pk_UserRace'))
    )
    # ### end Alembic commands ###

    bind = op.get_bind()
    session = orm.Session(bind=bind)
    Role.update_roles_permissions(session)
    Race.init(session)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserRace')
    op.drop_table('Race')
    # ### end Alembic commands ###
