"""v1

Revision ID: a2949a931135
Revises: 
Create Date: 2024-08-15 20:51:56.141464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2949a931135'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dialog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Dialog')),
    sa.UniqueConstraint('id', name=op.f('uq_Dialog_id'))
    )
    op.create_table('Game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('startStr', sa.String(length=8), server_default='16:30', nullable=False),
    sa.Column('duration', sa.Integer(), server_default='60', nullable=False),
    sa.Column('counter', sa.Integer(), server_default='150', nullable=False),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('clicks1', sa.Integer(), server_default='0', nullable=False),
    sa.Column('clicks2', sa.Integer(), server_default='0', nullable=False),
    sa.Column('winner', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Game')),
    sa.UniqueConstraint('id', name=op.f('uq_Game_id'))
    )
    op.create_table('GameLog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('startStr', sa.String(length=8), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('clicks1', sa.Integer(), nullable=True),
    sa.Column('clicks2', sa.Integer(), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_GameLog')),
    sa.UniqueConstraint('id', name=op.f('uq_GameLog_id'))
    )
    op.create_table('Image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Image')),
    sa.UniqueConstraint('id', name=op.f('uq_Image_id'))
    )
    op.create_table('Operation',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Operation')),
    sa.UniqueConstraint('id', name=op.f('uq_Operation_id'))
    )
    op.create_table('Role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Role')),
    sa.UniqueConstraint('id', name=op.f('uq_Role_id'))
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_big', sa.String(length=8), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('lastName', sa.String(length=128), nullable=True),
    sa.Column('imageUrl', sa.String(length=256), nullable=True),
    sa.Column('ticketType', sa.String(length=128), nullable=True),
    sa.Column('ticketTId', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('group', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_User')),
    sa.UniqueConstraint('id', name=op.f('uq_User_id')),
    sa.UniqueConstraint('id_big', name=op.f('uq_User_id_big'))
    )
    op.create_index(op.f('ix_User_login'), 'User', ['login'], unique=True)
    op.create_table('UserGameLog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gameId', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('lastClick', sa.DateTime(), nullable=True),
    sa.Column('hackAlert', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_UserGameLog')),
    sa.UniqueConstraint('id', name=op.f('uq_UserGameLog_id'))
    )
    op.create_table('DialogCharacter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('imgId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['imgId'], ['Image.id'], name=op.f('fk_DialogCharacter_imgId_Image')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_DialogCharacter')),
    sa.UniqueConstraint('id', name=op.f('uq_DialogCharacter_id'))
    )
    op.create_table('Log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('actionCode', sa.String(length=16), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=64), nullable=False),
    sa.Column('tableName', sa.String(length=16), nullable=False),
    sa.Column('recordId', sa.Integer(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('fk_Log_userId_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Log')),
    sa.UniqueConstraint('id', name=op.f('uq_Log_id'))
    )
    op.create_table('Permission',
    sa.Column('roleId', sa.Integer(), nullable=False),
    sa.Column('operationId', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['operationId'], ['Operation.id'], name=op.f('fk_Permission_operationId_Operation')),
    sa.ForeignKeyConstraint(['roleId'], ['Role.id'], name=op.f('fk_Permission_roleId_Role')),
    sa.PrimaryKeyConstraint('roleId', 'operationId', name=op.f('pk_Permission'))
    )
    op.create_table('Quest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_big', sa.String(length=8), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('dialog1Id', sa.Integer(), nullable=True),
    sa.Column('dialog2Id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dialog1Id'], ['Dialog.id'], name=op.f('fk_Quest_dialog1Id_Dialog')),
    sa.ForeignKeyConstraint(['dialog2Id'], ['Dialog.id'], name=op.f('fk_Quest_dialog2Id_Dialog')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Quest')),
    sa.UniqueConstraint('id', name=op.f('uq_Quest_id')),
    sa.UniqueConstraint('id_big', name=op.f('uq_Quest_id_big'))
    )
    op.create_table('Send',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_big', sa.String(length=8), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('creatorId', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('positive', sa.Boolean(), nullable=False),
    sa.Column('reusable', sa.Boolean(), nullable=False),
    sa.Column('used', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['creatorId'], ['User.id'], name=op.f('fk_Send_creatorId_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Send')),
    sa.UniqueConstraint('id', name=op.f('uq_Send_id')),
    sa.UniqueConstraint('id_big', name=op.f('uq_Send_id_big'))
    )
    op.create_table('StoreItem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_big', sa.String(length=8), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('imgId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['imgId'], ['Image.id'], name=op.f('fk_StoreItem_imgId_Image')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_StoreItem')),
    sa.UniqueConstraint('id', name=op.f('uq_StoreItem_id')),
    sa.UniqueConstraint('id_big', name=op.f('uq_StoreItem_id_big'))
    )
    op.create_table('Transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('fromId', sa.Integer(), nullable=False),
    sa.Column('toId', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fromId'], ['User.id'], name=op.f('fk_Transaction_fromId_User')),
    sa.ForeignKeyConstraint(['toId'], ['User.id'], name=op.f('fk_Transaction_toId_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Transaction')),
    sa.UniqueConstraint('id', name=op.f('uq_Transaction_id'))
    )
    op.create_table('UserGame',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('lastClick', sa.DateTime(), nullable=True),
    sa.Column('hackAlert', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('fk_UserGame_userId_User')),
    sa.PrimaryKeyConstraint('userId', name=op.f('pk_UserGame'))
    )
    op.create_table('UserRole',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('roleId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roleId'], ['Role.id'], name=op.f('fk_UserRole_roleId_Role')),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('fk_UserRole_userId_User')),
    sa.PrimaryKeyConstraint('userId', 'roleId', name=op.f('pk_UserRole'))
    )
    op.create_table('UserQuest',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('questId', sa.Integer(), nullable=False),
    sa.Column('openDate', sa.DateTime(), nullable=True),
    sa.Column('completeDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['questId'], ['Quest.id'], name=op.f('fk_UserQuest_questId_Quest')),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('fk_UserQuest_userId_User')),
    sa.PrimaryKeyConstraint('userId', 'questId', name=op.f('pk_UserQuest'))
    )
    op.create_table('UserSend',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('sendId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sendId'], ['Send.id'], name=op.f('fk_UserSend_sendId_Send')),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('fk_UserSend_userId_User')),
    sa.PrimaryKeyConstraint('userId', 'sendId', name=op.f('pk_UserSend'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserSend')
    op.drop_table('UserQuest')
    op.drop_table('UserRole')
    op.drop_table('UserGame')
    op.drop_table('Transaction')
    op.drop_table('StoreItem')
    op.drop_table('Send')
    op.drop_table('Quest')
    op.drop_table('Permission')
    op.drop_table('Log')
    op.drop_table('DialogCharacter')
    op.drop_table('UserGameLog')
    op.drop_index(op.f('ix_User_login'), table_name='User')
    op.drop_table('User')
    op.drop_table('Role')
    op.drop_table('Operation')
    op.drop_table('Image')
    op.drop_table('GameLog')
    op.drop_table('Game')
    op.drop_table('Dialog')
    # ### end Alembic commands ###
