"""v2

Revision ID: b87b040d03a8
Revises: a2949a931135
Create Date: 2024-08-15 21:00:38.729533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87b040d03a8'
down_revision: Union[str, None] = 'a2949a931135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DialogCharacter', sa.Column('orien', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DialogCharacter', 'orien')
    # ### end Alembic commands ###
