"""v2

Revision ID: 77173fe00cab
Revises: 09c1097e2e1e
Create Date: 2025-03-10 01:06:23.629236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77173fe00cab'
down_revision: Union[str, None] = '09c1097e2e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tourneyEnded', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('Tourney', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tourney', schema=None) as batch_op:
        batch_op.drop_column('ended')

    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.drop_column('tourneyEnded')

    # ### end Alembic commands ###
