"""v3

Revision ID: 21b3df4b7054
Revises: 27d9c8ac08b7
Create Date: 2026-08-09 13:02:32.998763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from bafser import get_datetime_now


# revision identifiers, used by Alembic.
revision: str = '21b3df4b7054'
down_revision: Union[str, None] = '27d9c8ac08b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=True))

    conn = op.get_bind()
    conn.execute(
        sa.text("UPDATE User SET createdAt = :d WHERE createdAt IS NULL"),
        {"d": get_datetime_now()},
    )

    with op.batch_alter_table("User", schema=None) as batch_op:
        batch_op.alter_column("createdAt", existing_type=sa.DateTime(), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('createdAt')

    # ### end Alembic commands ###
