"""v2

Revision ID: 27d9c8ac08b7
Revises: 9f8b80cda65d
Create Date: 2026-02-25 21:27:44.776666

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27d9c8ac08b7"
down_revision: Union[str, None] = "9f8b80cda65d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Game", schema=None) as batch_op:
        batch_op.add_column(sa.Column("startPhrase", sa.String(length=128), nullable=True))

    conn = op.get_bind()
    conn.execute(
        sa.text('UPDATE Game SET startPhrase = :phrase WHERE startPhrase IS NULL'),
        {"phrase": "Чтобы определить победителя приходите на сцену в $"},
    )

    with op.batch_alter_table("Game", schema=None) as batch_op:
        batch_op.alter_column("startPhrase", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Game", schema=None) as batch_op:
        batch_op.drop_column("startPhrase")

    # ### end Alembic commands ###
